// Generated by gencpp from file messages/ComputeDiskAreaResponse.msg
// DO NOT EDIT!


#ifndef MESSAGES_MESSAGE_COMPUTEDISKAREARESPONSE_H
#define MESSAGES_MESSAGE_COMPUTEDISKAREARESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace messages
{
template <class ContainerAllocator>
struct ComputeDiskAreaResponse_
{
  typedef ComputeDiskAreaResponse_<ContainerAllocator> Type;

  ComputeDiskAreaResponse_()
    : area(0.0)  {
    }
  ComputeDiskAreaResponse_(const ContainerAllocator& _alloc)
    : area(0.0)  {
  (void)_alloc;
    }



   typedef double _area_type;
  _area_type area;





  typedef boost::shared_ptr< ::messages::ComputeDiskAreaResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::messages::ComputeDiskAreaResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ComputeDiskAreaResponse_

typedef ::messages::ComputeDiskAreaResponse_<std::allocator<void> > ComputeDiskAreaResponse;

typedef boost::shared_ptr< ::messages::ComputeDiskAreaResponse > ComputeDiskAreaResponsePtr;
typedef boost::shared_ptr< ::messages::ComputeDiskAreaResponse const> ComputeDiskAreaResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::messages::ComputeDiskAreaResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::messages::ComputeDiskAreaResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::messages::ComputeDiskAreaResponse_<ContainerAllocator1> & lhs, const ::messages::ComputeDiskAreaResponse_<ContainerAllocator2> & rhs)
{
  return lhs.area == rhs.area;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::messages::ComputeDiskAreaResponse_<ContainerAllocator1> & lhs, const ::messages::ComputeDiskAreaResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::messages::ComputeDiskAreaResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages::ComputeDiskAreaResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::messages::ComputeDiskAreaResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::messages::ComputeDiskAreaResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::ComputeDiskAreaResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::ComputeDiskAreaResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::messages::ComputeDiskAreaResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "502b7bd5115b3b4f57d03446f9208d12";
  }

  static const char* value(const ::messages::ComputeDiskAreaResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x502b7bd5115b3b4fULL;
  static const uint64_t static_value2 = 0x57d03446f9208d12ULL;
};

template<class ContainerAllocator>
struct DataType< ::messages::ComputeDiskAreaResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "messages/ComputeDiskAreaResponse";
  }

  static const char* value(const ::messages::ComputeDiskAreaResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::messages::ComputeDiskAreaResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 area\n"
;
  }

  static const char* value(const ::messages::ComputeDiskAreaResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::messages::ComputeDiskAreaResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.area);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ComputeDiskAreaResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::messages::ComputeDiskAreaResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::messages::ComputeDiskAreaResponse_<ContainerAllocator>& v)
  {
    s << indent << "area: ";
    Printer<double>::stream(s, indent + "  ", v.area);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGES_MESSAGE_COMPUTEDISKAREARESPONSE_H
