// Generated by gencpp from file messages/ComputeDiskArea.msg
// DO NOT EDIT!


#ifndef MESSAGES_MESSAGE_COMPUTEDISKAREA_H
#define MESSAGES_MESSAGE_COMPUTEDISKAREA_H

#include <ros/service_traits.h>


#include <messages/ComputeDiskAreaRequest.h>
#include <messages/ComputeDiskAreaResponse.h>


namespace messages
{

struct ComputeDiskArea
{

typedef ComputeDiskAreaRequest Request;
typedef ComputeDiskAreaResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ComputeDiskArea
} // namespace messages


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::messages::ComputeDiskArea > {
  static const char* value()
  {
    return "c314357897f85c5c2498418b07dbcead";
  }

  static const char* value(const ::messages::ComputeDiskArea&) { return value(); }
};

template<>
struct DataType< ::messages::ComputeDiskArea > {
  static const char* value()
  {
    return "messages/ComputeDiskArea";
  }

  static const char* value(const ::messages::ComputeDiskArea&) { return value(); }
};


// service_traits::MD5Sum< ::messages::ComputeDiskAreaRequest> should match
// service_traits::MD5Sum< ::messages::ComputeDiskArea >
template<>
struct MD5Sum< ::messages::ComputeDiskAreaRequest>
{
  static const char* value()
  {
    return MD5Sum< ::messages::ComputeDiskArea >::value();
  }
  static const char* value(const ::messages::ComputeDiskAreaRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::messages::ComputeDiskAreaRequest> should match
// service_traits::DataType< ::messages::ComputeDiskArea >
template<>
struct DataType< ::messages::ComputeDiskAreaRequest>
{
  static const char* value()
  {
    return DataType< ::messages::ComputeDiskArea >::value();
  }
  static const char* value(const ::messages::ComputeDiskAreaRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::messages::ComputeDiskAreaResponse> should match
// service_traits::MD5Sum< ::messages::ComputeDiskArea >
template<>
struct MD5Sum< ::messages::ComputeDiskAreaResponse>
{
  static const char* value()
  {
    return MD5Sum< ::messages::ComputeDiskArea >::value();
  }
  static const char* value(const ::messages::ComputeDiskAreaResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::messages::ComputeDiskAreaResponse> should match
// service_traits::DataType< ::messages::ComputeDiskArea >
template<>
struct DataType< ::messages::ComputeDiskAreaResponse>
{
  static const char* value()
  {
    return DataType< ::messages::ComputeDiskArea >::value();
  }
  static const char* value(const ::messages::ComputeDiskAreaResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MESSAGES_MESSAGE_COMPUTEDISKAREA_H
