// Generated by gencpp from file messages/SetLed.msg
// DO NOT EDIT!


#ifndef MESSAGES_MESSAGE_SETLED_H
#define MESSAGES_MESSAGE_SETLED_H

#include <ros/service_traits.h>


#include <messages/SetLedRequest.h>
#include <messages/SetLedResponse.h>


namespace messages
{

struct SetLed
{

typedef SetLedRequest Request;
typedef SetLedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetLed
} // namespace messages


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::messages::SetLed > {
  static const char* value()
  {
    return "a5cba455e6c34810630dc8f80babd86a";
  }

  static const char* value(const ::messages::SetLed&) { return value(); }
};

template<>
struct DataType< ::messages::SetLed > {
  static const char* value()
  {
    return "messages/SetLed";
  }

  static const char* value(const ::messages::SetLed&) { return value(); }
};


// service_traits::MD5Sum< ::messages::SetLedRequest> should match
// service_traits::MD5Sum< ::messages::SetLed >
template<>
struct MD5Sum< ::messages::SetLedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::messages::SetLed >::value();
  }
  static const char* value(const ::messages::SetLedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::messages::SetLedRequest> should match
// service_traits::DataType< ::messages::SetLed >
template<>
struct DataType< ::messages::SetLedRequest>
{
  static const char* value()
  {
    return DataType< ::messages::SetLed >::value();
  }
  static const char* value(const ::messages::SetLedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::messages::SetLedResponse> should match
// service_traits::MD5Sum< ::messages::SetLed >
template<>
struct MD5Sum< ::messages::SetLedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::messages::SetLed >::value();
  }
  static const char* value(const ::messages::SetLedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::messages::SetLedResponse> should match
// service_traits::DataType< ::messages::SetLed >
template<>
struct DataType< ::messages::SetLedResponse>
{
  static const char* value()
  {
    return DataType< ::messages::SetLed >::value();
  }
  static const char* value(const ::messages::SetLedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MESSAGES_MESSAGE_SETLED_H
